# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0002_auto_20151227_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
