# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0003_auto_20151227_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='SERVER1', max_length=50),
            preserve_default=False,
        ),
    ]
