# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0004_server_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='params',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.CharField(default='csgo.exe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverinstance',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servermanager.Server'),
        ),
    ]
